export interface CountyInfo {
  county: string;
  sheriffUrl: string;
  jailUrl?: string;
  warrantUrl?: string;
}

export const CITY_COUNTY: Record<string, CountyInfo> = {
  'Birmingham, AL':   { county:'Jefferson County',  sheriffUrl:'https://www.jccal.org/Sites/Jefferson_County/pages/Sheriff/default.aspx' },
  'Montgomery, AL':   { county:'Montgomery County', sheriffUrl:'https://www.montgomerysheriff.com' },
  'Huntsville, AL':   { county:'Madison County',    sheriffUrl:'https://madisoncountysheriff.com' },
  'Mobile, AL':       { county:'Mobile County',     sheriffUrl:'https://www.mobileso.com' },
  'Tuscaloosa, AL':   { county:'Tuscaloosa County', sheriffUrl:'https://www.tuscaloosasheriff.org' },
  'Hoover, AL':       { county:'Jefferson County',  sheriffUrl:'https://www.jccal.org/Sites/Jefferson_County/pages/Sheriff/default.aspx' },
  'Dothan, AL':       { county:'Houston County',    sheriffUrl:'https://www.houstoncountyal.gov/sheriff' },
  'Auburn, AL':       { county:'Lee County',        sheriffUrl:'https://www.leecountyalsheriff.org' },
  'Decatur, AL':      { county:'Morgan County',     sheriffUrl:'https://www.morgancountysheriff.com' },
  'Madison, AL':      { county:'Madison County',    sheriffUrl:'https://madisoncountysheriff.com' },
  'Anchorage, AK':    { county:'Anchorage Municipality', sheriffUrl:'https://www.anchorageak.gov/police' },
  'Fairbanks, AK':    { county:'Fairbanks North Star Borough', sheriffUrl:'https://www.fnsb.gov/218/Sheriff' },
  'Juneau, AK':       { county:'City and Borough of Juneau', sheriffUrl:'https://www.juneau.org/police' },
  'Wasilla, AK':      { county:'Matanuska-Susitna Borough', sheriffUrl:'https://matsugov.us/departments/sheriff' },
  'Kenai, AK':        { county:'Kenai Peninsula Borough', sheriffUrl:'https://www.kpb.us/departments/sheriff' },
  'Phoenix, AZ':      { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Tucson, AZ':       { county:'Pima County',      sheriffUrl:'https://www.pimasheriff.org' },
  'Mesa, AZ':         { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Chandler, AZ':     { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Scottsdale, AZ':   { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Gilbert, AZ':      { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Glendale, AZ':     { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Tempe, AZ':        { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Peoria, AZ':       { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Surprise, AZ':     { county:'Maricopa County',  sheriffUrl:'https://www.mcso.org', warrantUrl:'https://www.mcso.org/Warrants' },
  'Little Rock, AR':  { county:'Pulaski County',   sheriffUrl:'https://www.pulaskisheriff.com' },
  'Fort Smith, AR':   { county:'Sebastian County', sheriffUrl:'https://sebastiancountysheriff.com' },
  'Fayetteville, AR': { county:'Washington County',sheriffUrl:'https://www.washingtoncoso.com' },
  'Springdale, AR':   { county:'Washington County',sheriffUrl:'https://www.washingtoncoso.com' },
  'Jonesboro, AR':    { county:'Craighead County', sheriffUrl:'https://www.craigheadcounty.org/sheriff' },
  'Conway, AR':       { county:'Faulkner County',  sheriffUrl:'https://www.faulknercountysheriff.com' },
  'Rogers, AR':       { county:'Benton County',    sheriffUrl:'https://www.bentoncountysheriff.com' },
  'Los Angeles, CA':  { county:'Los Angeles County',  sheriffUrl:'https://lasd.org' },
  'San Diego, CA':    { county:'San Diego County',    sheriffUrl:'https://www.sdsheriff.gov' },
  'San Jose, CA':     { county:'Santa Clara County',  sheriffUrl:'https://www.sccgov.org/sites/sheriff' },
  'San Francisco, CA':{ county:'San Francisco County',sheriffUrl:'https://www.sfsheriff.com' },
  'Fresno, CA':       { county:'Fresno County',       sheriffUrl:'https://www.fresnosheriff.org' },
  'Sacramento, CA':   { county:'Sacramento County',   sheriffUrl:'https://www.sacsheriff.com' },
  'Long Beach, CA':   { county:'Los Angeles County',  sheriffUrl:'https://lasd.org' },
  'Oakland, CA':      { county:'Alameda County',      sheriffUrl:'https://www.alamedacountysheriff.org' },
  'Bakersfield, CA':  { county:'Kern County',         sheriffUrl:'https://www.kernsheriff.com' },
  'Anaheim, CA':      { county:'Orange County',       sheriffUrl:'https://www.ocsd.org' },
  'Santa Ana, CA':    { county:'Orange County',       sheriffUrl:'https://www.ocsd.org' },
  'Riverside, CA':    { county:'Riverside County',    sheriffUrl:'https://www.rvcounty.org/sheriff' },
  'Stockton, CA':     { county:'San Joaquin County',  sheriffUrl:'https://www.sjsheriff.com' },
  'Chula Vista, CA':  { county:'San Diego County',    sheriffUrl:'https://www.sdsheriff.gov' },
  'Irvine, CA':       { county:'Orange County',       sheriffUrl:'https://www.ocsd.org' },
  'Denver, CO':       { county:'Denver County',      sheriffUrl:'https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Department-of-Safety/Sheriff-Division' },
  'Colorado Springs, CO': { county:'El Paso County', sheriffUrl:'https://www.epcsheriffsoffice.com' },
  'Aurora, CO':       { county:'Arapahoe County',    sheriffUrl:'https://www.arapahoesheriff.org' },
  'Fort Collins, CO': { county:'Larimer County',     sheriffUrl:'https://www.larimer.org/sheriff' },
  'Lakewood, CO':     { county:'Jefferson County',   sheriffUrl:'https://www.jeffco.us/1591/Sheriff' },
  'Thornton, CO':     { county:'Adams County',       sheriffUrl:'https://www.adamscountysheriff.org' },
  'Arvada, CO':       { county:'Jefferson County',   sheriffUrl:'https://www.jeffco.us/1591/Sheriff' },
  'Westminster, CO':  { county:'Adams County',       sheriffUrl:'https://www.adamscountysheriff.org' },
  'Pueblo, CO':       { county:'Pueblo County',      sheriffUrl:'https://www.pueblosheriff.com' },
  'Centennial, CO':   { county:'Arapahoe County',    sheriffUrl:'https://www.arapahoesheriff.org' },
  'Bridgeport, CT':   { county:'Fairfield County',   sheriffUrl:'https://portal.ct.gov/DESPP/Division-of-State-Police' },
  'New Haven, CT':    { county:'New Haven County',   sheriffUrl:'https://portal.ct.gov/DESPP/Division-of-State-Police' },
  'Stamford, CT':     { county:'Fairfield County',   sheriffUrl:'https://portal.ct.gov/DESPP/Division-of-State-Police' },
  'Hartford, CT':     { county:'Hartford County',    sheriffUrl:'https://portal.ct.gov/DESPP/Division-of-State-Police' },
  'Waterbury, CT':    { county:'New Haven County',   sheriffUrl:'https://portal.ct.gov/DESPP/Division-of-State-Police' },
  'Wilmington, DE':   { county:'New Castle County',  sheriffUrl:'https://www.nccde.org/225/Sheriff' },
  'Dover, DE':        { county:'Kent County',        sheriffUrl:'https://www.co.kent.de.us/sheriff.aspx' },
  'Newark, DE':       { county:'New Castle County',  sheriffUrl:'https://www.nccde.org/225/Sheriff' },
  'Jacksonville, FL': { county:'Duval County',       sheriffUrl:'https://www.jaxsheriff.org', warrantUrl:'https://www.jaxsheriff.org/services/warrant-search' },
  'Miami, FL':        { county:'Miami-Dade County',  sheriffUrl:'https://www.miamidade.gov/police' },
  'Tampa, FL':        { county:'Hillsborough County',sheriffUrl:'https://www.hcso.tampa.fl.us' },
  'Orlando, FL':      { county:'Orange County',      sheriffUrl:'https://www.ocfl.net/Sheriff' },
  'St. Petersburg, FL':{ county:'Pinellas County',   sheriffUrl:'https://www.pcsoweb.com' },
  'Hialeah, FL':      { county:'Miami-Dade County',  sheriffUrl:'https://www.miamidade.gov/police' },
  'Tallahassee, FL':  { county:'Leon County',        sheriffUrl:'https://www.leonso.com' },
  'Fort Lauderdale, FL':{ county:'Broward County',   sheriffUrl:'https://www.sheriff.org' },
  'Gainesville, FL':  { county:'Alachua County',     sheriffUrl:'https://www.alachuacounty.us/Depts/sheriff' },
  'Atlanta, GA':      { county:'Fulton County',      sheriffUrl:'https://www.fultonsheriff.org', warrantUrl:'https://www.fultoncountyga.gov/inside-fulton-county/fulton-county-departments/sheriff/warrants' },
  'Columbus, GA':     { county:'Muscogee County',    sheriffUrl:'https://www.columbusga.gov/sheriff' },
  'Augusta, GA':      { county:'Richmond County',    sheriffUrl:'https://www.augustaga.gov/454/Sheriffs-Office' },
  'Macon, GA':        { county:'Bibb County',        sheriffUrl:'https://www.maconbibb.us/sheriff' },
  'Savannah, GA':     { county:'Chatham County',     sheriffUrl:'https://www.chathamsheriff.com' },
  'Athens, GA':       { county:'Clarke County',      sheriffUrl:'https://www.accgov.com/sheriff' },
  'Boise, ID':        { county:'Ada County',         sheriffUrl:'https://www.adasheriff.org' },
  'Meridian, ID':     { county:'Ada County',         sheriffUrl:'https://www.adasheriff.org' },
  'Nampa, ID':        { county:'Canyon County',      sheriffUrl:'https://www.canyonco.org/elected-offices/sheriff' },
  'Idaho Falls, ID':  { county:'Bonneville County',  sheriffUrl:'https://www.co.bonneville.id.us/sheriff' },
  'Pocatello, ID':    { county:'Bannock County',     sheriffUrl:'https://www.bannockcounty.us/sheriff' },
  'Twin Falls, ID':   { county:'Twin Falls County',  sheriffUrl:'https://www.tfcounty.org/sheriff' },
  'Chicago, IL':      { county:'Cook County',        sheriffUrl:'https://www.cookcountysheriff.org' },
  'Aurora, IL':       { county:'Kane County',        sheriffUrl:'https://www.kanecountysheriff.com' },
  'Joliet, IL':       { county:'Will County',        sheriffUrl:'https://www.willcountysheriff.org' },
  'Rockford, IL':     { county:'Winnebago County',   sheriffUrl:'https://www.winnebagoilsheriff.com' },
  'Springfield, IL':  { county:'Sangamon County',    sheriffUrl:'https://www.sangamonsheriff.com' },
  'Naperville, IL':   { county:'DuPage County',      sheriffUrl:'https://www.dupagesheriff.org' },
  'Indianapolis, IN': { county:'Marion County',      sheriffUrl:'https://www.indy.gov/agency/marion-county-sheriffs-office' },
  'Fort Wayne, IN':   { county:'Allen County',       sheriffUrl:'https://www.allencountysheriff.org' },
  'Evansville, IN':   { county:'Vanderburgh County', sheriffUrl:'https://www.vanderburghsheriff.com' },
  'South Bend, IN':   { county:'St. Joseph County',  sheriffUrl:'https://www.sjcindiana.com/261/Sheriff' },
  'Des Moines, IA':   { county:'Polk County',        sheriffUrl:'https://www.polkcountysheriff.org' },
  'Cedar Rapids, IA': { county:'Linn County',        sheriffUrl:'https://www.linncounty.org/sheriff' },
  'Davenport, IA':    { county:'Scott County',       sheriffUrl:'https://www.scottcountysheriff.com' },
  'Sioux City, IA':   { county:'Woodbury County',    sheriffUrl:'https://www.woodburycountyiowa.gov/sheriff' },
  'Wichita, KS':      { county:'Sedgwick County',    sheriffUrl:'https://www.sedgwickcounty.org/sheriff' },
  'Overland Park, KS':{ county:'Johnson County',     sheriffUrl:'https://www.jocosheriff.org' },
  'Kansas City, KS':  { county:'Wyandotte County',   sheriffUrl:'https://www.wycokck.org/sheriff' },
  'Topeka, KS':       { county:'Shawnee County',     sheriffUrl:'https://www.snco.us/sheriff' },
  'Louisville, KY':   { county:'Jefferson County',   sheriffUrl:'https://www.louisvilleky.gov/government/metro-corrections' },
  'Lexington, KY':    { county:'Fayette County',     sheriffUrl:'https://www.fayettesheriff.com' },
  'Bowling Green, KY':{ county:'Warren County',      sheriffUrl:'https://www.warrencountysheriff.com' },
  'New Orleans, LA':  { county:'Orleans Parish',     sheriffUrl:'https://www.opcso.org', warrantUrl:'https://www.opcso.org/warrants' },
  'Baton Rouge, LA':  { county:'East Baton Rouge Parish', sheriffUrl:'https://www.ebrso.org' },
  'Shreveport, LA':   { county:'Caddo Parish',       sheriffUrl:'https://www.caddosheriff.org' },
  'Lafayette, LA':    { county:'Lafayette Parish',   sheriffUrl:'https://www.lafayettesheriff.com' },
  'Portland, ME':     { county:'Cumberland County',  sheriffUrl:'https://www.cumberlandsheriff.org' },
  'Lewiston, ME':     { county:'Androscoggin County',sheriffUrl:'https://www.androscoggincountysheriff.com' },
  'Bangor, ME':       { county:'Penobscot County',   sheriffUrl:'https://www.penobscotso.com' },
  'Baltimore, MD':    { county:'Baltimore City',     sheriffUrl:'https://www.baltimorecity.gov/offices/sheriff' },
  'Frederick, MD':    { county:'Frederick County',   sheriffUrl:'https://www.frederickcountymd.gov/sheriff' },
  'Rockville, MD':    { county:'Montgomery County',  sheriffUrl:'https://www.montgomerycountymd.gov/sheriff' },
  'Boston, MA':       { county:'Suffolk County',     sheriffUrl:'https://www.suffolksheriff.com' },
  'Worcester, MA':    { county:'Worcester County',   sheriffUrl:'https://www.worcestercountysheriff.com' },
  'Springfield, MA':  { county:'Hampden County',     sheriffUrl:'https://www.hampdensheriff.com' },
  'Detroit, MI':      { county:'Wayne County',       sheriffUrl:'https://www.waynecounty.com/elected/sheriff' },
  'Grand Rapids, MI': { county:'Kent County',        sheriffUrl:'https://www.accesskent.com/sheriff' },
  'Ann Arbor, MI':    { county:'Washtenaw County',   sheriffUrl:'https://www.washtenaw.org/sheriff' },
  'Lansing, MI':      { county:'Ingham County',      sheriffUrl:'https://www.inghamsheriff.org' },
  'Minneapolis, MN':  { county:'Hennepin County',    sheriffUrl:'https://www.hennepinsheriff.org' },
  'Saint Paul, MN':   { county:'Ramsey County',      sheriffUrl:'https://www.ramseycounty.us/residents/public-safety/sheriff' },
  'Rochester, MN':    { county:'Olmsted County',     sheriffUrl:'https://www.olmstedcountymn.gov/sheriff' },
  'Duluth, MN':       { county:'St. Louis County',   sheriffUrl:'https://www.stlouiscountymn.gov/sheriff' },
  'Jackson, MS':      { county:'Hinds County',       sheriffUrl:'https://www.hindscountysheriff.com' },
  'Gulfport, MS':     { county:'Harrison County',    sheriffUrl:'https://www.harrisoncountysheriff.com' },
  'Southaven, MS':    { county:'DeSoto County',      sheriffUrl:'https://www.desotocountysheriff.com' },
  'Hattiesburg, MS':  { county:'Forrest County',     sheriffUrl:'https://www.forrestcountysheriff.com' },
  'Kansas City, MO':  { county:'Jackson County',     sheriffUrl:'https://www.jacksongov.org/sheriff' },
  'Saint Louis, MO':  { county:'St. Louis City',     sheriffUrl:'https://www.stlouis-mo.gov/government/departments/sheriff' },
  'Springfield, MO':  { county:'Greene County',      sheriffUrl:'https://www.greenecountysheriff.org' },
  'Columbia, MO':     { county:'Boone County',       sheriffUrl:'https://www.showmeboone.com/sheriff' },
  'Billings, MT':     { county:'Yellowstone County', sheriffUrl:'https://www.yellowstonecountymt.gov/sheriff' },
  'Missoula, MT':     { county:'Missoula County',    sheriffUrl:'https://www.missoulacounty.us/sheriff' },
  'Bozeman, MT':      { county:'Gallatin County',    sheriffUrl:'https://www.gallatincounty.org/sheriff' },
  'Omaha, NE':        { county:'Douglas County',     sheriffUrl:'https://www.douglassheriff.org' },
  'Lincoln, NE':      { county:'Lancaster County',   sheriffUrl:'https://www.lancaster.ne.gov/sheriff' },
  'Bellevue, NE':     { county:'Sarpy County',       sheriffUrl:'https://www.sarpysheriff.org' },
  'Las Vegas, NV':    { county:'Clark County',       sheriffUrl:'https://www.lvmpd.com' },
  'Henderson, NV':    { county:'Clark County',       sheriffUrl:'https://www.lvmpd.com' },
  'Reno, NV':         { county:'Washoe County',      sheriffUrl:'https://www.washoesheriff.com' },
  'North Las Vegas, NV':{ county:'Clark County',     sheriffUrl:'https://www.lvmpd.com' },
  'Manchester, NH':   { county:'Hillsborough County',sheriffUrl:'https://www.hillsboroughsheriff.com' },
  'Nashua, NH':       { county:'Hillsborough County',sheriffUrl:'https://www.hillsboroughsheriff.com' },
  'Concord, NH':      { county:'Merrimack County',   sheriffUrl:'https://www.merrimacksheriff.com' },
  'Newark, NJ':       { county:'Essex County',       sheriffUrl:'https://www.essexcountynj.org/sheriff' },
  'Jersey City, NJ':  { county:'Hudson County',      sheriffUrl:'https://www.hudsoncountynj.org/sheriff' },
  'Paterson, NJ':     { county:'Passaic County',     sheriffUrl:'https://www.passaiccountynj.org/sheriff' },
  'Trenton, NJ':      { county:'Mercer County',      sheriffUrl:'https://www.mercercounty.org/sheriff' },
  'Albuquerque, NM':  { county:'Bernalillo County',  sheriffUrl:'https://www.bernalillocountysheriff.com' },
  'Las Cruces, NM':   { county:'Dona Ana County',    sheriffUrl:'https://www.donaanacounty.org/sheriff' },
  'Santa Fe, NM':     { county:'Santa Fe County',    sheriffUrl:'https://www.santafecountynm.gov/sheriff' },
  'New York City, NY':{ county:'New York City',      sheriffUrl:'https://www1.nyc.gov/site/sheriff/index.page' },
  'Buffalo, NY':      { county:'Erie County',        sheriffUrl:'https://www2.erie.gov/sheriff' },
  'Rochester, NY':    { county:'Monroe County',      sheriffUrl:'https://www.monroecounty.gov/sheriff' },
  'Syracuse, NY':     { county:'Onondaga County',    sheriffUrl:'https://www.ongov.net/sheriff' },
  'Albany, NY':       { county:'Albany County',      sheriffUrl:'https://www.albanycountysheriff.com' },
  'Charlotte, NC':    { county:'Mecklenburg County', sheriffUrl:'https://www.mecksheriff.com', warrantUrl:'https://www.mecksheriff.com/services/warrant-search' },
  'Raleigh, NC':      { county:'Wake County',        sheriffUrl:'https://www.wakegov.com/sheriff' },
  'Greensboro, NC':   { county:'Guilford County',    sheriffUrl:'https://www.guilfordcountync.gov/sheriff' },
  'Durham, NC':       { county:'Durham County',      sheriffUrl:'https://www.dursheriff.org' },
  'Winston-Salem, NC':{ county:'Forsyth County',     sheriffUrl:'https://www.forsythsheriff.org' },
  'Fargo, ND':        { county:'Cass County',        sheriffUrl:'https://www.casscountynd.gov/sheriff' },
  'Bismarck, ND':     { county:'Burleigh County',    sheriffUrl:'https://www.burleighco.com/sheriff' },
  'Columbus, OH':     { county:'Franklin County',    sheriffUrl:'https://www.franklincountysheriff.org', warrantUrl:'https://www.franklincountyohio.gov/Residents/Courts/Warrant-Search' },
  'Cleveland, OH':    { county:'Cuyahoga County',    sheriffUrl:'https://www.cuyahogasheriff.us' },
  'Cincinnati, OH':   { county:'Hamilton County',    sheriffUrl:'https://www.hcso.org' },
  'Toledo, OH':       { county:'Lucas County',       sheriffUrl:'https://www.lucascountysheriff.org' },
  'Akron, OH':        { county:'Summit County',      sheriffUrl:'https://www.co.summit.oh.us/sheriff' },
  'Oklahoma City, OK':{ county:'Oklahoma County',    sheriffUrl:'https://www.oklahomacountysheriff.com' },
  'Tulsa, OK':        { county:'Tulsa County',       sheriffUrl:'https://www.tulsacountysheriff.org' },
  'Norman, OK':       { county:'Cleveland County',   sheriffUrl:'https://www.clevelandcountyso.com' },
  'Portland, OR':     { county:'Multnomah County',   sheriffUrl:'https://multcosheriff.org' },
  'Salem, OR':        { county:'Marion County',      sheriffUrl:'https://www.co.marion.or.us/SO' },
  'Eugene, OR':       { county:'Lane County',        sheriffUrl:'https://www.lanecounty.org/sheriff' },
  'Bend, OR':         { county:'Deschutes County',   sheriffUrl:'https://www.deschutescountyso.com' },
  'Philadelphia, PA': { county:'Philadelphia County',sheriffUrl:'https://www.phillysheriff.com' },
  'Pittsburgh, PA':   { county:'Allegheny County',   sheriffUrl:'https://www.alleghenycountypa.gov/sheriff' },
  'Allentown, PA':    { county:'Lehigh County',      sheriffUrl:'https://www.lehighcountysheriff.com' },
  'Erie, PA':         { county:'Erie County',        sheriffUrl:'https://www.eriecountygov.org/sheriff' },
  'Harrisburg, PA':   { county:'Dauphin County',     sheriffUrl:'https://www.dauphinsheriff.com' },
  'Providence, RI':   { county:'Providence County',  sheriffUrl:'https://www.risha.ri.gov' },
  'Columbia, SC':     { county:'Richland County',    sheriffUrl:'https://www.rcsd.net' },
  'Charleston, SC':   { county:'Charleston County',  sheriffUrl:'https://www.charlestoncounty.org/departments/sheriff' },
  'Greenville, SC':   { county:'Greenville County',  sheriffUrl:'https://www.greenvillecounty.org/sheriff' },
  'Sioux Falls, SD':  { county:'Minnehaha County',   sheriffUrl:'https://www.minnehahacounty.org/sheriff' },
  'Rapid City, SD':   { county:'Pennington County',  sheriffUrl:'https://www.penningtoncounty.org/sheriff' },
  'Aberdeen, SD':     { county:'Brown County',       sheriffUrl:'https://www.brown.sd.gov/sheriff' },
  'Watertown, SD':    { county:'Codington County',   sheriffUrl:'https://www.codingtonco.org/sheriff' },
  'Mitchell, SD':     { county:'Davison County',     sheriffUrl:'https://www.davison-county.org/sheriff' },
  'Yankton, SD':      { county:'Yankton County',     sheriffUrl:'https://www.yanktoncounty.org/sheriff' },
  'Memphis, TN':      { county:'Shelby County',      sheriffUrl:'https://www.shelby-sheriff.org', warrantUrl:'https://warrants.shelby-sheriff.org/w_warrant_result.php', jailUrl:'https://imljail.shelbycountytn.gov/IML' },
  'Nashville, TN':    { county:'Davidson County',    sheriffUrl:'https://www.nashville.gov/Government/Courts/Sheriffs-Office.aspx' },
  'Knoxville, TN':    { county:'Knox County',        sheriffUrl:'https://www.knoxsheriff.org' },
  'Chattanooga, TN':  { county:'Hamilton County',    sheriffUrl:'https://www.hcsheriff.gov' },
  'Clarksville, TN':  { county:'Montgomery County',  sheriffUrl:'https://www.mcso-tn.org' },
  'Murfreesboro, TN': { county:'Rutherford County',  sheriffUrl:'https://www.rutherfordcso.com' },
  'Franklin, TN':     { county:'Williamson County',  sheriffUrl:'https://www.williamsonsheriff.org' },
  'Jackson, TN':      { county:'Madison County',     sheriffUrl:'https://www.madisoncountysheriff.com' },
  'Johnson City, TN': { county:'Washington County',  sheriffUrl:'https://www.washingtoncountysheriff.org' },
  'Kingsport, TN':    { county:'Sullivan County',    sheriffUrl:'https://www.sullivansheriff.com' },
  'Houston, TX':      { county:'Harris County',      sheriffUrl:'https://www.harriscountysheriff.org' },
  'San Antonio, TX':  { county:'Bexar County',       sheriffUrl:'https://www.bexar.org/sheriff', warrantUrl:'https://www.bexar.org/2408/Active-Warrants' },
  'Dallas, TX':       { county:'Dallas County',      sheriffUrl:'https://www.dallascounty.org/sheriff' },
  'Austin, TX':       { county:'Travis County',      sheriffUrl:'https://www.traviscountytx.gov/sheriff' },
  'Fort Worth, TX':   { county:'Tarrant County',     sheriffUrl:'https://www.tarrantcounty.com/sheriff' },
  'El Paso, TX':      { county:'El Paso County',     sheriffUrl:'https://www.epcounty.com/sheriff' },
  'Arlington, TX':    { county:'Tarrant County',     sheriffUrl:'https://www.tarrantcounty.com/sheriff' },
  'Corpus Christi, TX':{ county:'Nueces County',     sheriffUrl:'https://www.nuecessheriff.org' },
  'Plano, TX':        { county:'Collin County',      sheriffUrl:'https://www.collincountytx.gov/sheriff' },
  'Lubbock, TX':      { county:'Lubbock County',     sheriffUrl:'https://www.lubbocksheriff.org' },
  'Amarillo, TX':     { county:'Potter County',      sheriffUrl:'https://www.pottercountytx.org/sheriff' },
  'Brownsville, TX':  { county:'Cameron County',     sheriffUrl:'https://www.cameroncounty.us/sheriff' },
  'Salt Lake City, UT':{ county:'Salt Lake County',  sheriffUrl:'https://www.sheriff.slco.org' },
  'West Valley City, UT':{ county:'Salt Lake County',sheriffUrl:'https://www.sheriff.slco.org' },
  'Provo, UT':        { county:'Utah County',        sheriffUrl:'https://www.utahcounty.gov/dept/sheriff' },
  'West Jordan, UT':  { county:'Salt Lake County',   sheriffUrl:'https://www.sheriff.slco.org' },
  'Orem, UT':         { county:'Utah County',        sheriffUrl:'https://www.utahcounty.gov/dept/sheriff' },
  'Sandy, UT':        { county:'Salt Lake County',   sheriffUrl:'https://www.sheriff.slco.org' },
  'Ogden, UT':        { county:'Weber County',       sheriffUrl:'https://www.webercountyutah.gov/sheriff-office' },
  'St. George, UT':   { county:'Washington County',  sheriffUrl:'https://www.washco.utah.gov/sheriff' },
  'Layton, UT':       { county:'Davis County',       sheriffUrl:'https://www.daviscountyutah.gov/sheriff' },
  'Taylorsville, UT': { county:'Salt Lake County',   sheriffUrl:'https://www.sheriff.slco.org' },
  'South Jordan, UT': { county:'Salt Lake County',   sheriffUrl:'https://www.sheriff.slco.org' },
  'Lehi, UT':         { county:'Utah County',        sheriffUrl:'https://www.utahcounty.gov/dept/sheriff' },
  'Logan, UT':        { county:'Cache County',       sheriffUrl:'https://www.cachecounty.gov/sheriff' },
  'Burlington, VT':   { county:'Chittenden County',  sheriffUrl:'https://www.chittendensheriff.org' },
  'Virginia Beach, VA':{ county:'Virginia Beach City',sheriffUrl:'https://www.vbso.net' },
  'Norfolk, VA':      { county:'Norfolk City',       sheriffUrl:'https://www.norfolksheriff.com' },
  'Chesapeake, VA':   { county:'Chesapeake City',    sheriffUrl:'https://www.cityofchesapeake.net/sheriff' },
  'Richmond, VA':     { county:'Richmond City',      sheriffUrl:'https://www.rvasheriff.org' },
  'Newport News, VA': { county:'Newport News City',  sheriffUrl:'https://www.nnva.gov/sheriff' },
  'Seattle, WA':      { county:'King County',        sheriffUrl:'https://www.kingcounty.gov/depts/sheriff' },
  'Spokane, WA':      { county:'Spokane County',     sheriffUrl:'https://www.spokanesheriff.org' },
  'Tacoma, WA':       { county:'Pierce County',      sheriffUrl:'https://www.piercecountywa.gov/sheriff' },
  'Vancouver, WA':    { county:'Clark County',       sheriffUrl:'https://www.clark.wa.gov/sheriff' },
  'Bellevue, WA':     { county:'King County',        sheriffUrl:'https://www.kingcounty.gov/depts/sheriff' },
  'Everett, WA':      { county:'Snohomish County',   sheriffUrl:'https://www.snohomishcountywa.gov/sheriff' },
  'Charleston, WV':   { county:'Kanawha County',     sheriffUrl:'https://www.kanawhacountysheriff.com' },
  'Huntington, WV':   { county:'Cabell County',      sheriffUrl:'https://www.cabellsheriff.com' },
  'Morgantown, WV':   { county:'Monongalia County',  sheriffUrl:'https://www.monongaliacountysheriff.com' },
  'Milwaukee, WI':    { county:'Milwaukee County',   sheriffUrl:'https://county.milwaukee.gov/EN/Sheriff' },
  'Madison, WI':      { county:'Dane County',        sheriffUrl:'https://www.danesheriff.com' },
  'Green Bay, WI':    { county:'Brown County',       sheriffUrl:'https://www.browncountywi.gov/sheriff' },
  'Kenosha, WI':      { county:'Kenosha County',     sheriffUrl:'https://www.kenoshacountysheriff.us' },
  'Appleton, WI':     { county:'Outagamie County',   sheriffUrl:'https://www.outagamie.org/sheriff' },
  'Cheyenne, WY':     { county:'Laramie County',     sheriffUrl:'https://www.laramiecountysheriff.com' },
  'Casper, WY':       { county:'Natrona County',     sheriffUrl:'https://www.natronacountysheriff.com' },
  'Gillette, WY':     { county:'Campbell County',    sheriffUrl:'https://www.ccgov.net/sheriff' },
  'Washington, DC':   { county:'District of Columbia', sheriffUrl:'https://www.dccourts.gov/superior-court/civil-division/marshals-office' },
};
